config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
  resources :index do
    resources :photos, only: :show
  end
  root "static_pages#index"
    get 'privacy', to: 'static_pages#privacy'
    get 'team', to: 'static_pages#team'
    get 'career', to: 'static_pages#career'
    get 'about', to: 'static_pages#about'
    get 'faq', to: 'static_pages#faq'
    get 'contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  after_create :send_comment_email

  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :shop
  belongs_to :user
  has_many :photos
  mount_uploader :picture, PictureUploader
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true, length: {minimum: 3}
  validates :address, presence: true
  validates :description, presence: true, length: {maximum: 600}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shops
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @shop = Shop.find(params[:shop_id])
    @shop.comments.create(comment_params.merge(user: current_user))
    redirect_to shop_path(@shop)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @shop = Shop.find(params[:shop_id])
    @shop.photos.create(photo_params.merge(user: current_user))
    redirect_to shop_path(@shop)
  end

  def show
    render template: :photo
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    #@shops = Shop.all
    @shops = Shop.order("created_at DESC").paginate(page: params[:page], per_page:5)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.create(shop_params)
    if @shop.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @shop = Shop.find(params[:id])

    if @shop.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @shop.update_attributes(shop_params)
    if @shop.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    if @shop.user =! current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @shop.destroy
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :description, :address)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    #@shops = Shop.all
    @shops = Shop.order("created_at DESC").paginate(page: params[:page], per_page:5)
  end

  def career

  end

  def privacy

  end

  def team

  end

  def about

  end

  def faq

  end

  private

  def shop_params
    params.require(:shop).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Texas Carnivores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navbar Start -->
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Texas Carnivores', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to 'About us', about_path, class: 'nav-link' %>
            </li>

            <div class="dropdown show">
              <li class="nav-item">
                <%= link_to 'Local Shops', '#', class: 'nav-link dropdown-toggle', id: "dropdownMenuLink", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <%= link_to ' Shops Page', shops_path, class: 'dropdown-item nav-item fa fa-plus-circle' %>
                      <% if user_signed_in? %>
                        <%= link_to ' New Shop', new_shop_path, class: 'dropdown-item nav-item fa fa-plus-circle' %>
                      <% end %>
                  </div>
              </li>
            </div>

            <li class="nav-item">
              <%= link_to 'FAQ', faq_path, class: 'nav-link' %>
            </li>
            <!--<li class="nav-item">
              <%= link_to 'Southern Growing Tips', '#', class: 'nav-link' %>
            </li>-->
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Contact Us', contact_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <form class="form-inline my-2 my-lg-0">
              <%= link_to 'User Profile', user_path(current_user), class: 'nav-link' %>
            </form>
            <form class="form-inline my-2 my-lg-0">
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success my-2 my-sm-0' %>
            </form>
          <% else %>
            <form class="form-inline my-2 my-lg-0">
              <%= link_to 'Log in', new_user_session_path, class: 'btn btn-outline-success my-2 my-sm-0' %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-success my-2 my-sm-0' %>
            </form>
          <% end %>
        </div>
      </nav>
      <!-- Navbar End -->

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <div id="footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 col-sm-3">
              <h5>About</h5>
              <%= link_to 'Team', team_path %>
              <br/>
              <%= link_to 'Careers', career_path %>
              <br/>
              <%= link_to 'Privacy Policy', privacy_path %>
            </div>
            <div class="col-12 col-sm-3">
              <h5>Contact</h5>
              texascarnivores@gmail.com
              <br/>
              Austin, Tx
            </div>
            <div class="col-12 col-sm-3 social">
              <h5>Social</h5>
              <br/>
              <%= link_to 'https://github.com/jwlindsey/texas-carnivores' do %>
                <span class="fa fa-github-square fa-2x social-button"></span>
              <% end %>
              <%= link_to 'https://www.facebook.com/TexasCPC/' do %>
                <span class="fa fa-facebook-square fa-2x social-button">
              <% end %>
              <%= link_to 'https://twitter.com/TexasCPC' do %>
                <span class="fa fa-twitter-square fa-2x social-button"></span>
              <% end %>
              <%= link_to 'https://plus.google.com/u/1/106140595588716345357' do %>
                <span class="fa fa-google-plus-square fa-2x social-button"></span>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/shops/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Shop</h1>
  <%= simple_form_for @shop do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/shops/index.html.erb
<%= will_paginate @shops %>
<% @shops.each do |shop| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to shop.name, shop_path(shop) %></h1><br />
    <i><%= shop.address %></i><br /><br />
    <p><%= shop.description %></p><br />

    <% if shop.user.present? %>
      <small><%= shop.user.email %></small>
    <% end %>
  </div>

  <hr />
<% end %>

app/views/shops/new.html.erb
<div class='booyah-box col-10 offset-1'>
  <h1>details of the local shops go here</h1>
  <%= simple_form_for @shop do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/shops/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @shop.name %></h1>
  <i><%= @shop.address %></i>
  <br /><br />
  <p><%= @shop.description %></p>

<% if @shop.latitude.present? && @shop.longitude.present? %>

  <script>

    function initMap() {
      var myLatLng = {lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXMDDY6KGBvm5FOYqXBCiH0D9zhv7DEuE&callback=initMap">
  </script>

  <div id="map"></div>

<% end %>

  <br />

  <div class="float-right">
    <% if current_user && current_user == @shop.user %>
      <%= link_to 'Edit', edit_shop_path(@shop), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', shop_path(@shop), method: :delete, data: {confirm: 'Are you sure you want to delete this shop?'}, class: 'btn btn-danger' %>
    <% end %>
    <% if user_signed_in? %>
      <a href="#" id="show_comment_form" class="btn btn-primary">Comment</a>
    <% end %>
    <!-- Button trigger modal -->
    <button class="btn btn-primary" data-toggle="modal" data-target="#pictureModal">
      Add a photo
    </button>
  </div>
  <br />
  <br />
</div>

<script>
$(function() {
  $('a#show_comment_form').click(function(event){
    event.preventDefault();
    $('div#comment_box').toggle();
  });
});
</script>

<div class="clear"></div>
<div id="comment_box" class="hidden booyah-box col-10 offset-1">
  <%= simple_form_for @comment, url: shop_comments_path(@shop) do |f| %>
    <%= f.input :message %>
    <%= f.input :rating, as: :select, collection: Comment::RATINGS %>

    <%= f.submit "Add Comment", class: 'btn btn-primary' %>
  <% end %>
</div>
<div class="booyah-box col-10 offset-1">
  <h1>Comments</h1>

  <div class="row">
    <% @shop.comments.each do |comment| %>
      <div class="col-12 col-sm-6">
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b> -
          <% end %>
          <%= comment.message %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
</div>

<!-- Picture Modal -->
<div class="modal fade" id="pictureModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="pictureModalLabel">Add a Photo</h4>
      </div>

        <%= simple_form_for @photo, :url => shop_photos_path(@shop) do |f| %>
        <div class="modal-body">
          <%= f.input :picture %>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= f.submit "Add a Caption", class: 'btn btn-primary' %>
        </div>
          <% end %>
        </div>
      </div>
    </div>

<div class="booyah-box col-10 offset-1">
  <h1 class="pull-left">Photos</h1>
<!-- Button trigger modal -->
<!--<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#pictureModal">
  Add a photo
</button>-->

  <% @shop.photos.each do |photo| %>
    <div class="col-12 col-sm-6">
      <%= image_tag photo.picture, class: "img-fluid", alt: "Responsive image" %>
      <blockquote>
        <%= photo.caption %>
      </blockquote>
    </div>
  <% end %>
</div>
<!-- Picture modal end -->

app/views/static_pages/about.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>About</h1>

  <p>
     We are here to encourage communication and fellowship between fellow carnivorous plant enthusiasts. Promote the growth of carnivorous plants to any and all who will listen. As well as encourage the conservation of the local native species through cultivation.
  </p>
</div>

app/views/static_pages/career.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Careers</h1>

  <p>
    We are not looking to hire anyone at this time. If we experience a surge in growth then we may reconsider.
  </p>
</div>

app/views/static_pages/contact.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Contact Us</h1>
  <form type="text" required placeholder>
    <textarea name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>

</div>

app/views/static_pages/contact.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Contact Us</h1>
  <form type="text" required placeholder>
    <textarea name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>

</div>

app/views/static_pages/contact_test.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Contact Us</h1>

  <%= form_for @contact, url: create_contact_url do |f| %>

    <%= f.email_field @user.email %>
    <%= f.text_area :body, placeholder: 'body' %>
    <%= f.submit 'Send' %>
  <% end %>
</div>

app/views/static_pages/faq.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Frequently Asked Questions</h1>

  <ul class="list-unstyled font-weight-bold">
    Is it to hot in the south to grow carnivorous plants outdoors?
    <li class="font-weight-normal">
      Texas has many native carnivorous plant species and most of your cp's will thrive outdoors so long as you keep them moist.
    </li>
  </ul>
  <ul class="list-unstyled font-weight-bold">
    Should I keep my plants in the shade to protect them from the sun?
    <li class="font-weight-normal">
      That would depend on the species. Most full grown Sarracenia do just fine in full sun. However, you may want to give some partial shade to your younger species until they are fully hardened to the Texas heat. The same goes for your venus flytraps and sundews.
    </li>
  </ul>
  <ul class="list-unstyled font-weight-bold">
    I found some wild pitcher plants should I dig them up to try and assure their survival?
    <li class="font-weight-normal">
      Never dig up wild carnivorous plants unless you have permission from your local conservation office. We encourage saving species through propagation. So wait until the plant goes to seed and then collect the seed and sprout those. It may take longer but you won't damage their natural environment which causes more harm than good.
    </li>
  </ul>
</div>

app/views/static_pages/index.html.erb
<div>
  <br />
  <div class="col-10 offset-1 text-center image_1">
    <div class="box">
      <br />
      <h1 class="letters">Welcome to Texas Carnivores</h1>
      <br />
      <h2 class="letters">Meet ups in your local area</h2>
      <br />
      <h2 class="letters">Resources to help you raise your little CP's</h2>
      <% if user_signed_in? %>
        <br />
        <h2 class="letters">Feel free to explore!</h2>
        <br /><br />
      <% else %>
        <br />
        <%= link_to 'Join our community', new_user_registration_path , class: 'btn btn-success' %>
        <br /><br />
      <% end %>
    </div>
</div>

<br />
<div class="row">
  <div class="col-12 col-sm">
    <h3 class="letters">Amazing Community</h3>
    <br />
    <p>Find the help you need to raise your little carnivores. Wether you are just starting out or are a pro you are sure to find something helpful here.</p>
  </div>

  <div class="col-12 col-sm feature">
    <h3 class="letters">Find local stores</h3>
    <br />
    <p>It's always hard to find local places that sell carnivorous plants. It is always best if you can inspect the product yourself before purchasing. Our community is making an ever growing database of local Texas stores to help direct you to the closets nursery near you.</p>
  </div>

  <div class="col-12 col-sm">
    <h3 class="letters">Growing tips blog</h3>
    <br />
    <p>Being in Texas you know it is hotter here than most places. Our blog is full f tips to help deal with the heat and keep your little carnivores not only alive but thriving. </p>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Privacy Policy</h1>

  <p>
    Your personally identifiable information is protected to the best of our abilities. If you choose to join the community then we will share all non-personally identifiable information with the rest of the human race in our efforts to improve the lifestyles and growing habbits of human kind.
  </p>
</div>

app/views/static_pages/team.html.erb
<br />

<div class="booyah-box col-10 offset-1 text-center">
  <h1>Teams</h1>

  <p>
    We are hoping to encourage several of the local clubs in the major cities across Texas to be involved with this site in keeping it updated.
  </p>
</div>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="row">
    <div class='col-4'>
      <%= image_tag 'user.png' %>
    </div>

    <div class='col-8'>
      <h1><%= @user.email %></h1>
      <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4><%= @user.comments.count %> total comments</h4>
      <h4><%= @user.comments.where(rating: '5_stars').count %> total reviews</h4>
    </div>
  </div>
</div>

<div class='clear'></div>
<br /><br />

<div class="booyah-box col-10 offset-1">
  <h1 class='text-center'>My Comments</h1>
  <br /><br />
  <div class="row">
    <% @user.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <h2 class='text-center'><%= link_to comment.shop.name, shop_path(comment.shop) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
    <% end %>
  </div>
</div>

<div class='clear'></div>
<br /><br />

<div class="booyah-box col-10 offset-1">
  <h2 class='text-center'>My Shops</h2>
  <br /><br />
  <div class="row">
    <% @user.shops.each do |shop| %>
      <div class="booyah-box col-10 offset-1">
        <h1><%= link_to shop.name, shop_path(shop) %></h1>
        <i><%= shop.address %></i><br /><br />
        <p><%= shop.description %></p><br />
        <% if shop.photos.present? %>
          <%= image_tag shop.photos.last.picture, class:"image-box" %>
        <% end %>
        <% if shop.user.present? %>
          <small><%= shop.user.email %></small>
        <% end %>
      <% if shop.comments.present? %>
        <div class="col-12">
          <blockquote>
            <% if shop.comments.last.humanized_rating.present? %>
              <b><%= shop.comments.last.rating %></b> -
            <% end %>
            <%= shop.comments.last.message %>
            <small><%= shop.comments.last.user.email %></small>
          </blockquote>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>